export const 
AUTH_REQUEST 				= 'AUTH_REQUEST',
AUTH_SUCCESS 				= 'AUTH_SUCCESS',
AUTH_FAILURE 				= 'AUTH_FAILURE',
AUTH_LOGOUT 				= 'AUTH_LOGOUT',
AUTH_LOGOUT_REQUEST 		= 'AUTH_LOGOUT_REQUEST',
RECOVER_PASSWORD_REQUEST 	= 'RECOVER_PASSWORD_REQUEST',
FETCH_SITE_SETTINGS 		= 'FETCH_SITE_SETTINGS',
PROFILE_UPDATE_REQUEST 		= 'PROFILE_UPDATE_REQUEST',
PROFILE_UPDATE 				= 'PROFILE_UPDATE',
SITE_SETTINGS 				= 'SITE_SETTINGS';